# Generated by Django 5.2 on 2025-04-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='sms_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
