# Generated by Django 5.2 on 2025-04-23 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userverification_sms_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format international (ex: +33612345678).', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
    ]
