# Generated by Django 5.2 on 2025-04-27 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('transfer_sent', 'Transfert envoyé'), ('transfer_received', 'Transfert reçu'), ('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('profile_update', 'Profil mis à jour'), ('account_security', 'Sécurité du compte'), ('bill_payment', 'Paiement de facture'), ('system', 'Notification système')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='bell', max_length=50)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
